CREATE TABLE IF NOT EXISTS image (
id INTEGER PRIMARY KEY NOT NULL,
title VARCHAR(100) NOT NULL,
subtitle VARCHAR(250) NOT NULL,
created_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
updated_at  DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);